### ISSUE TITLE
Unable to read User input in Monster slayer

### ISSUE THREAD

**Issue by Mani-Vardhan-Kasthuri** [mschwarzmueller/golang-course-code#1]
All "if" conditions are failing in "interaction.GetUserChoice()" even if the user is entering valid Choices and the user is continuously prompted with "Fetching the user input failed. Please try again."

Using "go version go1.16.5 windows/amd64"

Solution
Insted of this
strings.Replace(userInput, "\n", "", -1) 
we need to use this
strings.Replace(userInput, "**\r**\n", "", -1)
and can further simplify to strings.**ReplaceAll**(userInput, "\r\n", "")

**Comment by ThomasChr** [comment]
You can check for windows with: 
```
if runtime.GOOS == "windows"
```
Do you want to fix this yourself and make a Pull Request for that?

Btw: The same problem seems to be with the bmi code from chapter 3!

**Comment by Mani-Vardhan-Kasthuri** [comment]
Hi @ThomasChr,
I have tried to raise PR but I did not have access to the same, if you provide me access I can raise PR.

Yes, the issue is there all the places where ever we are reading for cmd.

**Comment by ThomasChr** [comment]
You need to fork the repo (so you got your own copy) and fix it there. To make it simple you can fix it in your own master branch (no need to make an extra branch!). Then you can make a PR from there. Thats the workflow in nearly all github repos. You‘ll never get access to the original repo.

**Comment by ThomasChr** [comment]
@Mani-Vardhan-Kasthuri Do you know what to do? Can I help in any way?

I think that's a problem which should be fixed in the codebase, and a PR is just the right way to go!

**Comment by Mani-Vardhan-Kasthuri** [comment]
@ThomasChr Thank you for your help but I am not raising PR.

**Comment by ThomasChr** [comment]
@Mani-Vardhan-Kasthuri That's okay... But may I ask why?
I asked Jay from the discord chat (he discovered the same problem) if he would like to raise a PR.

If no one would like to to it, I will do it. I think this problem should be fixed.
@mschwarzmueller What do you think about that?

**Comment by mschwarzmueller** [comment]
Hi! Thanks for reporting this - really much appreciated! :)

I added some notes in the course (will update selected videos at a later point) and updated the code snapshots here on Github.

**Comment by ThomasChr** [comment]
To whoever is interessted, Max fixed it with this commit: https://github.com/mschwarzmueller/golang-course-code/commit/1c5a74f3cbf33e45a48813a68e8ba57f31d94371
